version: '3.8'

services:
  app:
    build: .
    container_name: kg-filter
    volumes:
      - ../:/kg_rag
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db_temp
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3309:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
